language: python
sudo: required
dist: xenial
python:
    - "3.5"
before_install:
    - /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416
    - sudo dpkg -i ./keyring.deb
    - echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | sudo tee /etc/apt/sources.list.d/sur5r-i3.list > /dev/null
    - sudo apt-get update -qq
    - sudo apt-get install xvfb i3
    - sudo pip install pytest
script: ./run-tests.py
